"""Initial migration

Revision ID: d979b6c66bb8
Revises: 
Create Date: 2024-08-31 23:25:10.825081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd979b6c66bb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('prenume', sa.String(length=150), nullable=True),
    sa.Column('nume', sa.String(length=150), nullable=True),
    sa.Column('ani', sa.Integer(), nullable=True),
    sa.Column('boala', sa.String(length=500), nullable=True),
    sa.Column('medicamente', sa.String(length=500), nullable=True),
    sa.Column('ultimul_incident', sa.String(length=500), nullable=True),
    sa.Column('tara', sa.String(length=100), nullable=True),
    sa.Column('judet', sa.String(length=100), nullable=True),
    sa.Column('oras', sa.String(length=100), nullable=True),
    sa.Column('strada', sa.String(length=200), nullable=True),
    sa.Column('numar', sa.String(length=50), nullable=True),
    sa.Column('cod_postal', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('este_logat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('dispatcher')
    op.drop_table('accident')
    # ### end Alembic commands ###
