"""Add data_nasterii to Patient model

Revision ID: 582277b1d914
Revises: fcc945df53ee
Create Date: 2024-09-01 01:58:35.020658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582277b1d914'
down_revision = 'fcc945df53ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nasterii', sa.Date(), nullable=True))
        batch_op.drop_column('ani')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ani', sa.INTEGER(), nullable=True))
        batch_op.drop_column('data_nasterii')

    # ### end Alembic commands ###
