"""Add telefon column to Patient model

Revision ID: fcc945df53ee
Revises: d979b6c66bb8
Create Date: 2024-09-01 01:35:04.319656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc945df53ee'
down_revision = 'd979b6c66bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefon', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('telefon')

    # ### end Alembic commands ###
